server:
  port: 9999
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: bootteach
  servlet:
    multipart:
      enabled: true
  #数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/bootteachsystem?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
    activiti:
      #    false:默认，数据库表不变，但是如果版本不对或者缺失表会抛出异常（生产使用）
      #    true:表不存在，自动创建（开发使用）
      #    create_drop: 启动时创建，关闭时删除表（测试使用）
      #    drop_create: 启动时删除表,在创建表 （不需要手动关闭引擎）
      database-schema-update: true
      #监测历史表是否存在，activities7默认不开启历史表
      db-history-used: true
      #none：不保存任何历史数据，流程中这是最高效的
      #activity：只保存流程实例和流程行为
      #audit：除了activity，还保存全部的流程任务以及其属性，audit为history默认值
      #full：除了audit、还保存其他全部流程相关的细节数据，包括一些流程参数
      history-level: full
      #校验流程文件，默认校验resources下的process 文件夹的流程文件
      check-process-definitions: true

  #es搜索引擎
  elasticsearch:
    rest:
      uris: http://192.168.219.137:9200
  #开启bean重复定义重写
  main:
    allow-bean-definition-overriding: false
  #rabbitmq
  rabbitmq:
    host: 192.168.219.137
    port: 5672
    publisherReturns: true
    publisher-confirm-type: correlated
  #redis配置
  redis:
    host: 192.168.219.137
    port: 6379

#文件统一存储minio
minio:
  accessHost: http://192.168.219.137:9000
  bucket: bootteach
  accessKey: admin
  secretKey: admin123456
JWT:
  secretKey: $QWERTYUIOP!AAZXCVBNMDGJJKKLNNV<?
  #jwt 令牌有效期 单位毫秒
  ttlMillis: 360000
  #jwt 令牌有效天数
  expDay: 1
es:
  serverHost: http://192.168.219.137:9200

#mybatis
mybatis-plus:
  global-config:
    banner: on
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#swagger文档开启/关闭
springfox:
  documentation:
    auto-startup: true
#knife4j
knife4j:
  production: false # 开启/屏蔽文档资源
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.219.137:8848
        file-extension: yaml #指定yml文件
    config:
      server-addr: 192.168.219.138:8848
