version: "3.5"

services:
#  mall4cloud-mysql:
#    image: mysql:8.0
#    container_name: mall4cloud-mysql
#    restart: always
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#    ports:
#      - 3306:3306
#    volumes:
#      - ./mysql/data:/var/lib/mysql
#      - ./mysql/my.cnf:/etc/mysql/my.cnf
#      - ./mysql/initdb:/docker-entrypoint-initdb.d
#      - ./mysql/mysql-files:/var/lib/mysql-files

  teach-minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    container_name: teach-minio
    restart: always
    command: server /data
    ports:
      - 9000:9000
    volumes:
      - /home/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123456
#
#  teach-redis:
#    image: redis:6.2
#    container_name: teach-redis
#    restart: always
#    ports:
#      - 6379:6379
#
#
#  teach-elasticsearch:
#    image: elasticsearch:7.13.2
#    container_name: teach-elasticsearch
#    restart: always
#    ports:
#      - 9200:9200
#      - 9300:9300
#    environment:
#      - discovery.type=single-node
#      - ES_JAVA_OPTS=-Xms512m -Xmx512m
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#      - ./elasticsearch/data:/usr/share/elasticsearch/data
#      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
#
#  teach-kibana:
#    image: kibana:7.13.2
#    container_name: teach-kibana
#    restart: always
#    ports:
#      - 5601:5601
#    links:
#      - mall4cloud-elasticsearch:elasticsearch
#    depends_on:
#      - mall4cloud-elasticsearch
#
#  teach-canal:
#    image: canal/canal-server:v1.1.5
#    container_name: teach-canal
#    restart: always
#    ports:
#      - 11111:11111
#    environment:
#      - SEATA_IP=192.168.219.136
#    volumes:
#      - ./canal/conf/example:/home/admin/canal-server/conf/example
#      - ./canal/conf/canal.properties:/home/admin/canal-server/conf/canal.properties
#      - ./canal/logs:/home/admin/canal-server/logs
#
#
#
#
#  teach-rocketmq-namesrv:
#    image: foxiswho/rocketmq:4.8.0
#    container_name: teach-rocketmq-namesrv
#    restart: always
#    ports:
#      - 9876:9876
#    volumes:
#      - ./rocketmq/namesrv/logs:/home/rocketmq/logs
#      - ./rocketmq/namesrv/store:/home/rocketmq/store
#    environment:
#      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128m"
#    command: ["sh","mqnamesrv"]
#    networks:
#      rocketmq:
#        aliases:
#          - teach-rocketmq-namesrv
#
#
#  mall4cloud-rocketmq-broker:
#    image: foxiswho/rocketmq:4.8.0
#    container_name: teach-rocketmq-broker
#    restart: always
#    ports:
#      - 10909:10909
#      - 10911:10911
#    volumes:
#      - ./rocketmq/broker/logs:/home/rocketmq/logs
#      - ./rocketmq/broker/store:/home/rocketmq/store
#      - ./rocketmq/broker/conf/broker.conf:/etc/rocketmq/broker.conf
#    environment:
#      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128m"
#    command: ["sh","mqbroker","-c","/etc/rocketmq/broker.conf","-n","mall4cloud-rocketmq-namesrv:9876","autoCreateTopicEnable=true"]
#    depends_on:
#      - teach-rocketmq-namesrv
#    networks:
#      rocketmq:
#        aliases:
#          - teach-rocketmq-broker
#
#
#  mall4cloud-rocketmq-console:
#    image: styletang/rocketmq-console-ng
#    container_name: teach-rocketmq-console
#    restart: always
#    ports:
#      - 8180:8080
#    environment:
#      JAVA_OPTS: "-Drocketmq.namesrv.addr=teach-rocketmq-namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
#    depends_on:
#      - teach-rocketmq-namesrv
#    networks:
#      rocketmq:
#        aliases:
#          - teach-rocketmq-console
#
#
#networks:
#  rocketmq:
#    name: rocketmq
#    driver: bridge
